/*
 * Copyright (c) 2024 Infineon Technologies AG. All Rights Reserved.
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG, its affiliates or its licensees. If and as long as no
 * such terms of use are agreed, use of this file is subject to the Evaluation Software License Agreement distributed
 * along with this file within the software delivery package.
 *
 */

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/
#include "Ifx_MDA_VToFController_F16.h"
#include "Ifx_MDA_VToFController_F16_Cfg.h"

/* C library */
#include "stddef.h"

/* Math library includes */
#include "Ifx_Math_Arithmetic_F16.h"

/******************************************************************************/
/*-----------------------------------Macros-----------------------------------*/
/******************************************************************************/
/* Macros to define the component ID */
#define IFX_MDA_VTOFCONTROLLER_F16_COMPONENTID_SOURCEID     ((uint8_t)Ifx_ComponentID_SourceID_infineonTechnologiesAG)
#define IFX_MDA_VTOFCONTROLLER_F16_COMPONENTID_LIBRARYID    ((uint16_t)Ifx_ComponentID_LibraryID_mctrlDriveAlgorithm)
#define IFX_MDA_VTOFCONTROLLER_F16_COMPONENTID_MODULEID     (4U)
#define IFX_MDA_VTOFCONTROLLER_F16_COMPONENTID_COMPONENTID1 (1U)

#define IFX_MDA_VTOFCONTROLLER_F16_COMPONENTID_COMPONENTID2 ((uint8_t)Ifx_ComponentID_ComponentID2_basic)

/* Macros to define the component version */
#define IFX_MDA_VTOFCONTROLLER_F16_COMPONENTVERSION_MAJOR   (2U)
#define IFX_MDA_VTOFCONTROLLER_F16_COMPONENTVERSION_MINOR   (0U)
#define IFX_MDA_VTOFCONTROLLER_F16_COMPONENTVERSION_PATCH   (0U)
#define IFX_MDA_VTOFCONTROLLER_F16_COMPONENTVERSION_T       (4U)
#define IFX_MDA_VTOFCONTROLLER_F16_COMPONENTVERSION_REV     (0U)

/******************************************************************************/
/*-----------------------Private Function Prototypes--------------------------*/
/******************************************************************************/
/* API to convert speed to voltage amplitude */
static inline Ifx_Math_Fract16 Ifx_MDA_VToFController_F16_LUT(Ifx_MDA_VToFController_F16_VToFLutNorm* vTofLutNorm,
                                                              Ifx_Math_Fract16                        speedQ15);

/* API to interpolate between two points in a LUT */
static inline Ifx_Math_Fract16 Ifx_MDA_VToFController_F16_interp(Ifx_Math_Fract16 absc1, Ifx_Math_Fract16 absc2,
                                                                 Ifx_Math_Fract16 ord1, Ifx_Math_Fract16 ord2,
                                                                 Ifx_Math_Fract16 abscIn);

/* API to generate the electrical angle output */
static inline uint32_t Ifx_MDA_VToFController_F16_angleCalc(Ifx_MDA_VToFController_F16* self, Ifx_Math_Fract16
                                                            speedQ15);

/******************************************************************************/
/*------------------------Private Variables/Constants-------------------------*/
/******************************************************************************/
/* *INDENT-OFF* */
/* Component ID */
static const Ifx_ComponentID      Ifx_MDA_VToFController_F16_componentID = {
    .sourceID     = IFX_MDA_VTOFCONTROLLER_F16_COMPONENTID_SOURCEID,
    .libraryID    = IFX_MDA_VTOFCONTROLLER_F16_COMPONENTID_LIBRARYID,
    .moduleID     = IFX_MDA_VTOFCONTROLLER_F16_COMPONENTID_MODULEID,
    .componentID1 = IFX_MDA_VTOFCONTROLLER_F16_COMPONENTID_COMPONENTID1,
    .componentID2 = IFX_MDA_VTOFCONTROLLER_F16_COMPONENTID_COMPONENTID2,
};

/* Component Version */
static const Ifx_ComponentVersion Ifx_MDA_VToFController_F16_componentVersion = {
    .major = IFX_MDA_VTOFCONTROLLER_F16_COMPONENTVERSION_MAJOR,
    .minor = IFX_MDA_VTOFCONTROLLER_F16_COMPONENTVERSION_MINOR,
    .patch = IFX_MDA_VTOFCONTROLLER_F16_COMPONENTVERSION_PATCH,
    .t     = IFX_MDA_VTOFCONTROLLER_F16_COMPONENTVERSION_T,
    .rev   = IFX_MDA_VTOFCONTROLLER_F16_COMPONENTVERSION_REV
};

/******************************************************************************/
/*-----------------------Exported Variables/Constants-------------------------*/
/******************************************************************************/
/* temporary solution, XML_VERSION indicates if static cfg is generated by cfgwiz */
#ifdef IFX_MDA_VTOFCONTROLLER_F16_CFG_XML_VERSION
Ifx_MDA_VToFController_F16_Param Ifx_MDA_VToFController_F16_g_defaultParam = 
{
    .VToFLUTnorm =
    {
        .ratedSpeedQ15 = IFX_MDA_VTOFCONTROLLER_F16_CFG_RATED_SPEED,
        .cornerSpeedQ15 = IFX_MDA_VTOFCONTROLLER_F16_CFG_CORNER_SPEED,
        .ratedVoltQ15 = IFX_MDA_VTOFCONTROLLER_F16_CFG_V2RATED_SPEED,
        .cornerVoltQ15 = IFX_MDA_VTOFCONTROLLER_F16_CFG_V2CORNER_SPEED,
        .minVoltQ15 = IFX_MDA_VTOFCONTROLLER_F16_CFG_V2MIN_SPEED,
    },
    .angleIncrementQ14 = (Ifx_Math_Fract16)IFX_MDA_VTOFCONTROLLER_F16_CFG_ANGLE_INC_Q14,
};
#endif
/* *INDENT-ON* */
/******************************************************************************/
/*-------------------------Function Implementations---------------------------*/
/******************************************************************************/
/* Function to get the component ID */
void Ifx_MDA_VToFController_F16_getID(const Ifx_ComponentID** componentID)
{
    *componentID = &Ifx_MDA_VToFController_F16_componentID;
}


/* Function to get the component version */
void Ifx_MDA_VToFController_F16_getVersion(const Ifx_ComponentVersion** componentVersion)
{
    *componentVersion = &Ifx_MDA_VToFController_F16_componentVersion;
}


/* Initialize parameters of the module */
void Ifx_MDA_VToFController_F16_init(Ifx_MDA_VToFController_F16* self, Ifx_MDA_VToFController_F16_Param* param)
{
    /* Initialize pointer to parameter structure */
    self->param = param;

    /* Initialize the angle state */
    self->p_anglePreviousValue = 0;

    /* Initialize amplitude of the output voltage vector */
    self->p_output.voltageVector.amplitude = 0;

    /* Initialize angle of the output voltage vector */
    self->p_output.voltageVector.angle = 0;
}


/* Calculate the amplitude and angle of the voltage vector */
void Ifx_MDA_VToFController_F16_execute(Ifx_MDA_VToFController_F16* self, Ifx_Math_Fract16 speedQ15)
{
    /* Operations: */
    /* Interpolate to get the voltage amplitude */
    self->p_output.voltageVector.amplitude = Ifx_MDA_VToFController_F16_LUT(&self->param->VToFLUTnorm,
        Ifx_Math_Abs_F16(speedQ15));

    /* Integrate the rate limited input speed */
    self->p_output.voltageVector.angle = Ifx_MDA_VToFController_F16_angleCalc(self, speedQ15);
}


static inline Ifx_Math_Fract16 Ifx_MDA_VToFController_F16_LUT(Ifx_MDA_VToFController_F16_VToFLutNorm* vTofLutNorm,
                                                              Ifx_Math_Fract16                        speedQ15)
{
    /* Local variable to store temporary result */
    Ifx_Math_Fract16 voltVectAmpN;

    /* Check in which range is the input speed */
    if (speedQ15 > vTofLutNorm->cornerSpeedQ15)
    {
        /* Interpolate in the second range */
        voltVectAmpN = Ifx_MDA_VToFController_F16_interp(vTofLutNorm->cornerSpeedQ15, vTofLutNorm->ratedSpeedQ15,
            vTofLutNorm->cornerVoltQ15, vTofLutNorm->ratedVoltQ15, speedQ15);
    }
    else
    {
        /* Interpolate in the first range */
        voltVectAmpN = Ifx_MDA_VToFController_F16_interp(0, vTofLutNorm->cornerSpeedQ15, vTofLutNorm->minVoltQ15,
            vTofLutNorm->cornerVoltQ15, speedQ15);
    }

    return voltVectAmpN;
}


static inline Ifx_Math_Fract16 Ifx_MDA_VToFController_F16_interp(Ifx_Math_Fract16 absc1, Ifx_Math_Fract16 absc2,
                                                                 Ifx_Math_Fract16 ord1, Ifx_Math_Fract16 ord2,
                                                                 Ifx_Math_Fract16 abscIn)
{
    /* Local variable to store delta x */
    Ifx_Math_Fract16 deltaX;

    /* Local variable to store delta y */
    Ifx_Math_Fract16 deltaY;

    /* Local variable to store x - x1 */
    Ifx_Math_Fract16 deltaIn;

    /* Local variable to store the result */
    Ifx_Math_Fract16 result;

    /* Local variable to store the result of the division */
    Ifx_Math_Fract16 deltaYX;
    deltaX  = Ifx_Math_Sub_F16(absc2, absc1);
    deltaY  = Ifx_Math_Sub_F16(ord2, ord1);
    deltaIn = Ifx_Math_Sub_F16(abscIn, absc1);

    /* del_in/del_X, Q15, using DivSat limits the output to rated voltage */
    deltaYX = Ifx_Math_DivSat_F16(deltaIn, deltaX);

    /* Interpolated voltage, Q15 */
    result = Ifx_Math_Add_F16(Ifx_Math_Mul_F16(deltaYX, deltaY), ord1);

    return result;
}


static inline uint32_t Ifx_MDA_VToFController_F16_angleCalc(Ifx_MDA_VToFController_F16* self, Ifx_Math_Fract16
                                                            speedQ15)
{
    /* Local variables for electrical angle change, electrical frequency and temporary Angle */
    Ifx_Math_Fract32 electricalAngleDelta;

    /* Calculate the delTheta = normalized speed x normalized factor */
    electricalAngleDelta = Ifx_Math_MulShL_F32_F16F16(speedQ15, self->param->angleIncrementQ14, 3u);

    /* Total electrical angle after change */
    if (electricalAngleDelta >= 0)
    {
        self->p_anglePreviousValue = self->p_anglePreviousValue + (uint32_t)electricalAngleDelta;
    }
    else
    {
        self->p_anglePreviousValue = self->p_anglePreviousValue - (uint32_t)(Ifx_Math_Neg_F32(electricalAngleDelta));
    }

    /* Calculate the output */
    return self->p_anglePreviousValue;
}
