/*
 * Copyright (c) 2024 Infineon Technologies AG. All Rights Reserved.
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG, its affiliates or its licensees. If and as long as no
 * such terms of use are agreed, use of this file is subject to the Evaluation Software License Agreement distributed
 * along with this file within the software delivery package.
 *
 */

/**
 * \file Ifx_MHA_BEMFComparators_F16_TLE987.h
 * \brief A specialized Back EMF control module for the TLE987x devices
 * This module processes the back emf comparator signals generated by the BEMF Comparators hardware module.
 */

#ifndef IFX_MHA_BEMFCOMPARATORS_F16_TLE987_H
#define IFX_MHA_BEMFCOMPARATORS_F16_TLE987_H
#include "Ifx_ComponentID.h"
#include "Ifx_ComponentVersion.h"
#include "Ifx_Math.h"
#include "stdbool.h"
#include "stdint.h"

/**
 * Module state machine states
 */
typedef enum Ifx_MHA_BEMFComparators_F16_TLE987_State
{
    Ifx_MHA_BEMFComparators_F16_TLE987_State_init     = 0, /**<Initialization state*/
    Ifx_MHA_BEMFComparators_F16_TLE987_State_off      = 1, /**<Off state*/
    Ifx_MHA_BEMFComparators_F16_TLE987_State_debounce = 2, /**<Debouncing state*/
    Ifx_MHA_BEMFComparators_F16_TLE987_State_onPos    = 3, /**<Run state in positive direction*/
    Ifx_MHA_BEMFComparators_F16_TLE987_State_onNeg    = 4, /**<Run state in negative direction*/
} Ifx_MHA_BEMFComparators_F16_TLE987_State;

/**
 * Status of the module containing state machine state
 */
typedef struct Ifx_MHA_BEMFComparators_F16_TLE987_Status
{
    /**
     * State of the state machine
     */
    Ifx_MHA_BEMFComparators_F16_TLE987_State state;

    /**
     * Flag to indicate whether the BEMF comparator signals are valid
     */
    bool isSignalValid;
} Ifx_MHA_BEMFComparators_F16_TLE987_Status;

/**
 * \brief Data structure that stores all data of module instance.
 */
typedef struct Ifx_MHA_BEMFComparators_F16_TLE987
{
    /**
     * State of each phase
     */
    Ifx_Math_3PhaseFract16 bemfComparatorState;

    /**
     * Status of the module
     */
    Ifx_MHA_BEMFComparators_F16_TLE987_Status status;

    /**
     * Debounce counter
     */
    int32_t debounceCounter;

    /**
     * Standstill counter
     */
    uint32_t standstillCounter;

    /**
     * Old Sector
     */
    uint8_t oldSector;

    /**
     * Current sector
     */
    uint8_t actualSector;

    /**
     * State machine enable setting
     */
    bool enable;
} Ifx_MHA_BEMFComparators_F16_TLE987;

/**
 *  \brief Returns the component ID
 *
 *  \param [out] *componentID Variable to store the address of the component ID
 */
void Ifx_MHA_BEMFComparators_F16_TLE987_getID(const Ifx_ComponentID** componentID);

/**
 *  \brief Returns the component version
 *
 *  \param [out] *componentVersion Variable to store the address of the component version
 */
void Ifx_MHA_BEMFComparators_F16_TLE987_getVersion(const Ifx_ComponentVersion** componentVersion);

/**
 *  \brief Execute the state machine of the module
 *
 *  \param [inout] self Reference to structure that contains instance data members
 */
void Ifx_MHA_BEMFComparators_F16_TLE987_execute(Ifx_MHA_BEMFComparators_F16_TLE987* self);

/**
 *  \brief Initialize the module
 *
 *  \param [inout] self Reference to structure that contains instance data members
 */
void Ifx_MHA_BEMFComparators_F16_TLE987_init(Ifx_MHA_BEMFComparators_F16_TLE987* self);

/**
 *  \brief This API enables or disables the module based on the input parameter enable.
 *
 *  If the input parameter is TRUE and no fault is detected, then the module will be
 *  enabled in the next call to execute().
 *
 *  \param [inout] self Reference to structure that contains instance data members
 *
 *  \param [in] enable Parameter of boolean type to enable or disable the module
 */
static inline void Ifx_MHA_BEMFComparators_F16_TLE987_enable(Ifx_MHA_BEMFComparators_F16_TLE987* self, bool enable)
{
    self->enable = enable;
}


#endif /*IFX_MHA_BEMFCOMPARATORS_F16_TLE987_H*/
