/*
 * Copyright (c) 2024 Infineon Technologies AG. All Rights Reserved.
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG, its affiliates or its licensees. If and as long as no
 * such terms of use are agreed, use of this file is subject to the Evaluation Software License Agreement distributed
 * along with this file within the software delivery package.
 *
 */

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/
#include "Ifx_MDA_IToFController_F16.h"
#include "Ifx_MDA_IToFController_F16_Cfg.h"

/* C library */
#include "stddef.h"

/* Math library includes */
#include "Ifx_Math_Arithmetic_F16.h"

/******************************************************************************/
/*-----------------------------------Macros-----------------------------------*/
/******************************************************************************/
/* Macros to define the component ID */
#define IFX_MDA_ITOFCONTROLLER_F16_COMPONENTID_SOURCEID     ((uint8_t)Ifx_ComponentID_SourceID_infineonTechnologiesAG)
#define IFX_MDA_ITOFCONTROLLER_F16_COMPONENTID_LIBRARYID    ((uint16_t)Ifx_ComponentID_LibraryID_mctrlDriveAlgorithm)
#define IFX_MDA_ITOFCONTROLLER_F16_COMPONENTID_MODULEID     (2U)
#define IFX_MDA_ITOFCONTROLLER_F16_COMPONENTID_COMPONENTID1 (1U)

#define IFX_MDA_ITOFCONTROLLER_F16_COMPONENTID_COMPONENTID2 ((uint8_t)Ifx_ComponentID_ComponentID2_basic)

/* Macros to define the component version */
#define IFX_MDA_ITOFCONTROLLER_F16_COMPONENTVERSION_MAJOR   (2U)
#define IFX_MDA_ITOFCONTROLLER_F16_COMPONENTVERSION_MINOR   (0U)
#define IFX_MDA_ITOFCONTROLLER_F16_COMPONENTVERSION_PATCH   (0U)
#define IFX_MDA_ITOFCONTROLLER_F16_COMPONENTVERSION_T       (4U)
#define IFX_MDA_ITOFCONTROLLER_F16_COMPONENTVERSION_REV     (0U)

/******************************************************************************/
/*-----------------------Private Function Prototypes--------------------------*/
/******************************************************************************/
/* API to generate the electrical angle output */
static inline uint32_t Ifx_MDA_IToFController_F16_angleCalc(Ifx_MDA_IToFController_F16* self, Ifx_Math_Fract16
                                                            speedQ15);

/******************************************************************************/
/*------------------------Private Variables/Constants-------------------------*/
/******************************************************************************/
/* *INDENT-OFF* */
/* Component ID */
static const Ifx_ComponentID      Ifx_MDA_IToFController_F16_componentID = {
    .sourceID     = IFX_MDA_ITOFCONTROLLER_F16_COMPONENTID_SOURCEID,
    .libraryID    = IFX_MDA_ITOFCONTROLLER_F16_COMPONENTID_LIBRARYID,
    .moduleID     = IFX_MDA_ITOFCONTROLLER_F16_COMPONENTID_MODULEID,
    .componentID1 = IFX_MDA_ITOFCONTROLLER_F16_COMPONENTID_COMPONENTID1,
    .componentID2 = IFX_MDA_ITOFCONTROLLER_F16_COMPONENTID_COMPONENTID2,
};

/* Component Version */
static const Ifx_ComponentVersion Ifx_MDA_IToFController_F16_componentVersion = {
    .major = IFX_MDA_ITOFCONTROLLER_F16_COMPONENTVERSION_MAJOR,
    .minor = IFX_MDA_ITOFCONTROLLER_F16_COMPONENTVERSION_MINOR,
    .patch = IFX_MDA_ITOFCONTROLLER_F16_COMPONENTVERSION_PATCH,
    .t     = IFX_MDA_ITOFCONTROLLER_F16_COMPONENTVERSION_T,
    .rev   = IFX_MDA_ITOFCONTROLLER_F16_COMPONENTVERSION_REV
};

/******************************************************************************/
/*-----------------------Exported Variables/Constants-------------------------*/
/******************************************************************************/
/* temporary solution, XML_VERSION indicates if static cfg is generated by cfgwiz */
#ifdef IFX_MDA_ITOFCONTROLLER_F16_CFG_XML_VERSION
/* Default parameters initialized with CfgWizard defines */
Ifx_MDA_IToFController_F16_Param Ifx_MDA_IToFController_F16_g_defaultParam =
{
    .angleIncrementQ14 = IFX_MDA_ITOFCONTROLLER_F16_CFG_ANGLE_INC_Q14,    
};
#endif
/* *INDENT-ON* */
/******************************************************************************/
/*-------------------------Function Implementations---------------------------*/
/******************************************************************************/
/* Function to get the component ID */
void Ifx_MDA_IToFController_F16_getID(const Ifx_ComponentID** componentID)
{
    *componentID = &Ifx_MDA_IToFController_F16_componentID;
}


/* Function to get the component version */
void Ifx_MDA_IToFController_F16_getVersion(const Ifx_ComponentVersion** componentVersion)
{
    *componentVersion = &Ifx_MDA_IToFController_F16_componentVersion;
}


/* Initialize parameters of the module */
void Ifx_MDA_IToFController_F16_init(Ifx_MDA_IToFController_F16* self, Ifx_MDA_IToFController_F16_Param* param)
{
    /* Initialize pointer to parameter structure */
    self->param = param;

    /* Initialize the angle state */
    self->p_anglePreviousValue = 0U;

    /* Initialize real reference current */
    self->p_output.refCurrent.real = 0;
}


/* Adds 180 degree in the current value of angle*/
void Ifx_MDA_IToFController_F16_addOneEightyDegreeInAngle(Ifx_MDA_IToFController_F16* self)
{
    Ifx_MDA_IToFController_F16_setAnglePreviousValue(self, self->p_output.currentVecAngle_rad + IFX_MATH_PI_INDEX);
}


/* Calculate the angle of the current vector */
void Ifx_MDA_IToFController_F16_execute(Ifx_MDA_IToFController_F16* self, Ifx_Math_Fract16 speedQ15)
{
    /* Operations: */
    /* Integrate the rate limited input speed */
    self->p_output.currentVecAngle_rad = Ifx_MDA_IToFController_F16_angleCalc(self, speedQ15);
}


static inline uint32_t Ifx_MDA_IToFController_F16_angleCalc(Ifx_MDA_IToFController_F16* self, Ifx_Math_Fract16
                                                            speedQ15)
{
    /* Local variables for electrical angle change, electrical frequency and temporary Angle */
    Ifx_Math_Fract32 electricalAngleDelta;

    /* Calculate the delTheta = normalized speed x normalized factor */
    electricalAngleDelta = Ifx_Math_MulShL_F32_F16F16(speedQ15, self->param->angleIncrementQ14, 3u);

    /* Total electrical angle after change */
    if (electricalAngleDelta >= 0)
    {
        self->p_anglePreviousValue = self->p_anglePreviousValue + (uint32_t)electricalAngleDelta;
    }
    else
    {
        self->p_anglePreviousValue = self->p_anglePreviousValue - (uint32_t)(Ifx_Math_Neg_F32(electricalAngleDelta));
    }

    /* Calculate the output */
    return self->p_anglePreviousValue;
}
