/*
 * Copyright (c) 2024 Infineon Technologies AG. All Rights Reserved.
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG, its affiliates or its licensees. If and as long as no
 * such terms of use are agreed, use of this file is subject to the Evaluation Software License Agreement distributed
 * along with this file within the software delivery package.
 *
 */

/**
 * \file Ifx_MHA_PatternGen_F16_TLE987.h
 * \brief A specialized pattern generator component for TLE987x devices.
 * Sets the compare values needed by the CCU6 hardware module that drives the switches of the bridge driver, as well as
 * the compare value needed by the hardware module to trigger a current measurement (compare values are mainly
 * calculated by the modulator). It sets the modulation frequency and the deadtime of the system. In addition to that,
 * it can be configured to react on a trap fault.
 */

#ifndef IFX_MHA_PATTERNGEN_F16_TLE987_H
#define IFX_MHA_PATTERNGEN_F16_TLE987_H
#include "Ifx_ComponentID.h"
#include "Ifx_ComponentVersion.h"
#include "Ifx_MHA_PatternGen_F16_TLE987_Cfg.h"
#include "ccu6.h"
#include "stdbool.h"
#include "stdint.h"

/**
 * Macro for dead time conversion from nano second to micro second
 */
#define IFX_MHA_PATTERNGEN_F16_TLE987_NANO_TO_MICRO               (1000)

/**
 * Macro for converting frequency from MHz to kHz
 */
#define IFX_MHA_PATTERNGEN_F16_TLE987_MHZ_TO_KHZ                  (1000)

/**
 * Macro for fault reaction when fault source is disabled
 */
#define IFX_MHA_PATTERNGEN_F16_TLE987_FAULT_REACTION_DISABLE      (0)

/**
 * Macro for fault reaction when fault source is enabled
 */
#define IFX_MHA_PATTERNGEN_F16_TLE987_FAULT_REACTION_ENABLE       (1)

/**
 * Macro for fault reaction when fault source is report only
 */
#define IFX_MHA_PATTERNGEN_F16_TLE987_FAULT_REACTION_REPORT_ONLY  (2)

/**
 * Macro for fault reaction when fault source is report and react
 */
#define IFX_MHA_PATTERNGEN_F16_TLE987_FAULT_REACTION_REPORT_REACT (3)

/**
 * Pattern generator state options
 */
typedef enum Ifx_MHA_PatternGen_F16_TLE987_State
{
    Ifx_MHA_PatternGen_F16_TLE987_State_init  = 0, /**<Pattern generator is initialized.*/
    Ifx_MHA_PatternGen_F16_TLE987_State_off   = 1, /**<Pattern generator is disabled. */
    Ifx_MHA_PatternGen_F16_TLE987_State_on    = 2, /**<Pattern generator is enabled.*/
    Ifx_MHA_PatternGen_F16_TLE987_State_fault = 3, /**<Pattern generator is in fault.*/
} Ifx_MHA_PatternGen_F16_TLE987_State;

/**
 * Status of the pattern generator, containing the bit coded errors and the state machine state
 */
typedef struct Ifx_MHA_PatternGen_F16_TLE987_Status
{
    /**
     * Status of the pattern generator
     */
    Ifx_MHA_PatternGen_F16_TLE987_State state;

    /**
     * TRAP status flag
     */
    bool trap;
} Ifx_MHA_PatternGen_F16_TLE987_Status;

/**
 * \brief Data structure that stores all data of module instance.
 */
typedef struct Ifx_MHA_PatternGen_F16_TLE987
{
    /**
     * State machine enable setting
     */
    bool p_enable;

    /**
     * State machine fault clear setting
     */
    bool p_clearFault;

    /**
     * Array to store the compare values
     */
    uint16_t p_compareValues_tick[6];

    /**
     * Array to store the compare shadow values
     */
    uint16_t p_compareValuesShadow_tick[6];

    /**
     * Array to store the trigger times values
     */
    uint16_t p_triggerTime_tick[2];

    /**
     * Array to store the shadow trigger times values
     */
    uint16_t p_triggerTimeShadow_tick[2];

    /**
     * Status of the pattern generator, containing the bit coded errors and the state machine state
     */
    Ifx_MHA_PatternGen_F16_TLE987_Status p_status;

    /**
     * Counter of the current control cycles
     */
    uint8_t p_cycleCounter;

    /**
     * Flags that the pattern generator execute function has finished its execution
     */
    bool p_executed;
} Ifx_MHA_PatternGen_F16_TLE987;

/**
 *  \brief Handles the PatternGen state machine.
 *
 *  Additionally, it takes the compare values and the triggers in ticks generated by
 *  another component (e.g. space vector modulation) and writes these values to the
 *  corresponding hardware configuration registers.
 *
 *  Inputs of this API:
 *  <ul>
 *  <li>Status bit of the Trap fault of the pattern generator interrupt status
 *  register. The fault is considered by fault detection only if it is configured
 *  for FAULT_REPORT_REACT</li>
 *  </ul>
 *  <ul>
 *  <li>State machine "Enable" input, boolean data that is Enabled/Disabled by a
 *  call to the Ifx_MHA_PatternGen_F16_TLE987_enable(true/false)</li>
 *  </ul>
 *
 *  Outputs of this API:
 *  <ul>
 *  <li>State variable: encoded on the "Status" output</li>
 *  </ul>
 *  <ul>
 *  <li>Error code: encoded on the "Status" output</li>
 *  </ul>
 *
 *  These outputs are set corresponding to the states and state transitions design.
 *  A fault, if it is not disabled, will be detected and the configured action will
 *  be taken within 3 calls to this function.
 *
 *  \param [inout] self Reference to structure that contains instance data members
 *
 *  \param [in] compareValues[6] Compare values for the switches: first three up count, second three down count
 *
 *  \param [in] triggerTime_tick[2] Array of first and second time trigger, in clock ticks
 */
void Ifx_MHA_PatternGen_F16_TLE987_execute(Ifx_MHA_PatternGen_F16_TLE987* self, uint16_t compareValues[6], uint16_t
                                           triggerTime_tick[2]);

/**
 *  \brief Initializes the PatternGen.
 *
 *  The default CCU6 peripheral initialization should be done by the user before
 *  calling this function.
 *  This function will overwrite selected CCU6 registers dependent on the static
 *  configuration.
 *  The timer has to be started by the user before the first call to the execute
 *  function.
 *  All private variables except of the trigger times are initialized either to zero
 *  or to the statically configured values. The first trigger time is initialized to
 *  "2" (just after the start of the PWM period) because the Timer3, which is used
 *  for the first trigger, is running at half of the frequency of the CCU6. The
 *  second trigger time is initialized to the middle of the PWM period. This ensures
 *  that the current measurement is triggered in every state.
 *
 *  \param [inout] self Reference to structure that contains instance data members
 */
void Ifx_MHA_PatternGen_F16_TLE987_init(Ifx_MHA_PatternGen_F16_TLE987* self);

/**
 *  \brief Enables or disables the PatternGen.
 *
 *  If the input parameter is true and no fault is detected, then the PatternGen
 *  will be enabled in the next call to execute().
 *  Enabling sets the HW-related members of the internal "self" data structure to
 *  the corresponding HW registers according to the user manual.
 *
 *  \param [inout] self Reference to structure that contains instance data members
 *
 *  \param [in] enable Can be true to enable or false to disable
 */
static inline void Ifx_MHA_PatternGen_F16_TLE987_enable(Ifx_MHA_PatternGen_F16_TLE987* self, bool enable)
{
    self->p_enable = enable;
}


/**
 *  \brief This function has to be called on the one match interrupt by the library user.
 *
 *  This will update the timer compare values and trigger times for the second half
 *  of the PWM cycle.
 *
 *  \param [inout] self Reference to structure that contains instance data members
 */
void Ifx_MHA_PatternGen_F16_TLE987_onOneMatch(Ifx_MHA_PatternGen_F16_TLE987* self);

/**
 *  \brief Clears all faults.
 *
 *  The PatternGen will be set to enable or disable state in the next call to
 *  execute() depending on the enable setting. New hardware fault will lead to fault
 *  state again.
 *
 *  \param [inout] self Reference to structure that contains instance data members
 */
static inline void Ifx_MHA_PatternGen_F16_TLE987_clearFault(Ifx_MHA_PatternGen_F16_TLE987* self)
{
    self->p_clearFault = true;
}


/**
 *  \brief This function has to be called in the period match interrupt by the library
 *  user.
 *
 *  This will update the timer compare values and trigger times for the first half
 *  of the PWM cycle.
 *
 *  \param [inout] self Reference to structure that contains instance data members
 */
void Ifx_MHA_PatternGen_F16_TLE987_onPeriodMatch(Ifx_MHA_PatternGen_F16_TLE987* self);

/**
 *  \brief Check if a clear fault request is pending.
 *
 *  \param [inout] self Reference to structure that contains instance data members
 *
 *  \return True if a clear fault request was made but still not processed by the module and
 * False otherwise
 */
static inline bool Ifx_MHA_PatternGen_F16_TLE987_clearFaultIsPending(Ifx_MHA_PatternGen_F16_TLE987* self)
{
    return self->p_clearFault;
}


/**
 *  \brief Reset the variables used to count the number of execution cycles.
 *
 *  Used to synchronize the current control loop with the Pattern Generator
 *  execution.
 *
 *  \param [inout] self Reference to structure that contains instance data members
 */
static inline void Ifx_MHA_PatternGen_F16_TLE987_reset(Ifx_MHA_PatternGen_F16_TLE987* self)
{
    self->p_cycleCounter = 0;
    self->p_executed     = false;
}


/**
 *  \brief Get the status of the pattern generator.
 *
 *  The status variable contains the bit coded errors and the state machine state.
 *
 *  \param [inout] self Reference to structure that contains instance data members
 *
 *  \return Pattern generator status
 */
static inline Ifx_MHA_PatternGen_F16_TLE987_Status Ifx_MHA_PatternGen_F16_TLE987_getStatus(
    Ifx_MHA_PatternGen_F16_TLE987* self)
{
    return self->p_status;
}


/**
 *  \brief Set the dead time value in ns.
 *
 *  Range: [minDeadTime...255/T12_CLK] (at 40MHz: [minDeadTime...6375ns])
 *  Resolution: 1/T12_CLK (at 40MHz: 25ns)
 *
 *  \param [inout] self Reference to structure that contains instance data members
 *
 *  \param [in] deadTime_ns Dead time value, in nanoseconds
 */
void Ifx_MHA_PatternGen_F16_TLE987_setDeadTime_ns(Ifx_MHA_PatternGen_F16_TLE987* self, uint32_t deadTime_ns);

/**
 *  \brief Get the pattern generator dead time value in nanoseconds.
 *
 *  \param [inout] self Reference to structure that contains instance data members
 *
 *  \return Dead time value, in nanoseconds
 */
uint32_t Ifx_MHA_PatternGen_F16_TLE987_getDeadTime_ns(Ifx_MHA_PatternGen_F16_TLE987* self);

/**
 *  \brief Set the pattern generator frequency in kHz.
 *
 *  This function sets the pattern generator frequency in between 1kHz and 40kHz
 *  with a resolution of 1kHz.
 *  Changes to the switching frequency will only be applied during 'off' or 'init'
 *  state. During every other state, a setting of this dynamic configuration will be
 *  ignored!
 *
 *  \param [inout] self Reference to structure that contains instance data members
 *
 *  \param [in] frequency_kHz Frequency in kHz
 */
void Ifx_MHA_PatternGen_F16_TLE987_setFrequency_kHz(Ifx_MHA_PatternGen_F16_TLE987* self, uint32_t frequency_kHz);

/**
 *  \brief Get the configured frequency in kHz.
 *
 *  \param [inout] self Reference to structure that contains instance data members
 *
 *  \return Frequency, in kHz
 */
uint32_t Ifx_MHA_PatternGen_F16_TLE987_getFrequency_kHz(Ifx_MHA_PatternGen_F16_TLE987* self);

/**
 *  \brief Returns the component ID
 *
 *  \param [out] *componentID Variable to store the address of the component ID
 */
void Ifx_MHA_PatternGen_F16_TLE987_getID(const Ifx_ComponentID** componentID);

/**
 *  \brief Returns the component version
 *
 *  \param [out] *componentVersion Variable to store the address of the component version
 */
void Ifx_MHA_PatternGen_F16_TLE987_getVersion(const Ifx_ComponentVersion** componentVersion);

#endif /*IFX_MHA_PATTERNGEN_F16_TLE987_H*/
